# Generated by Django 4.0.6 on 2022-07-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateTimeField(verbose_name='Время отправления')),
                ('arrivalTime', models.DateTimeField(verbose_name='Время прибытия')),
                ('travelTime', models.DateTimeField(verbose_name='Время в пути')),
                ('drivingMode', models.TextField(verbose_name='Режим движения')),
                ('trainRoute', models.TextField(verbose_name='Маршрут электрички')),
                ('priceAtCheckout', models.PositiveIntegerField(verbose_name='Цена при покупке в кассе')),
                ('TroikaCardPrice', models.PositiveIntegerField(verbose_name="Цена по карте 'Тройка'")),
                ('delaysInfo', models.TextField(verbose_name='Информация о задержках')),
                ('Link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
