# Generated by Django 4.0.6 on 2022-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrivalTime',
            field=models.DateTimeField(verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departureTime',
            field=models.DateTimeField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travelTime',
            field=models.TextField(verbose_name='Время в пути'),
        ),
    ]
