# Generated by Django 4.0.6 on 2022-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tparser', '0002_alter_schedule_options_alter_schedule_arrivaltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='TroikaCardPrice',
            field=models.PositiveIntegerField(verbose_name='Цена по карте "Тройка"'),
        ),
    ]
