# Generated by Django 4.0.6 on 2022-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tparser', '0005_alter_schedule_arrivaltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='delaysInfo',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о задержках'),
        ),
    ]
