# Generated by Django 4.0.6 on 2022-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tparser', '0006_alter_schedule_delaysinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания электричек Тушинская → Стрешнево (бывш. Ленинградская) на сегодня'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='isTrainGone',
            field=models.BooleanField(default=False, verbose_name='Ушёл ли поезд'),
        ),
    ]
