# Generated by Django 4.0.6 on 2022-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tparser', '0007_alter_schedule_options_schedule_istraingone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='isTrainGone',
            field=models.BooleanField(blank=True, verbose_name='Ушёл ли поезд'),
        ),
    ]
